### ISSUE TITLE
Add version number to JSON file

### ISSUE THREAD

**Issue by gquerret** [clement-brodu/PCTTools#5]
In order to be able to deal with upgrades of the library, would it be possible to have a `version` attribute in the JSON output ?

```
{
  "version": 1,
  "classes": [
    {
      "name": "Microsoft.Win32.Registry",
      "baseTypes": [ "System.Object" ]
    }
}
```

**Comment by clement-brodu** [comment]
The version you need is more a "schema Version" than "library version", right ?

This version number must be incremented only in case of adding/removing/modifying something in the model ?

**Comment by gquerret** [comment]
Yes, schema version. This is to make sure the LS will correctly read data. File will be deleted in case of outdated schema, and notification sent to the user.

**Comment by clement-brodu** [comment]
done,
